# MLFlow related ----------------------------------------------------------------
MODEL_NAME: "cr_poverty"

# Model related ----------------------------------------------------------------

# Dependent variable
OUTCOME_VARIABLE: Target

# poverty level mapping
POVERTY_MAPPING:
  1: extreme
  2: moderate
  3: vulnerable
  4: not vulnerable


# Number of hyperparameter optimization trials that are run concurrently across Spark executor nodes
# REF: https://www.databricks.com/blog/2021/04/15/how-not-to-tune-your-model-with-hyperopt.html
PARALLELISM: 10

# Timeout seconds for each SparkTrial
TIMEOUT_SECONDS: 7200

# CV scheme

# Fraction of the data to be used as the test set (aka holdout set)
TEST_SIZE: 0.3
# Number of cross validation folds
N_FOLDS: 2
# Number of iterations for the hyperparameter search
N_ITER: 100

# Fraction of the test set to be further split and be used as the calibration set
CALIBRATION_SIZE: 0.5
# Flags to enable calibration
PERFORM_CALIBRATION: True
# Calibration method: sigmoid or isotonic
CALIBRATION_METHOD: sigmoid

# Flag to enable learning curves plotting
PLOT_LEARNING_CURVES: True

PLOT_SHAP_VALUES: True
SHAP_THRESHOLD: 5 # threshold for which to filter out outliers (abs)
SHAP_TYPE: beeswarm # beeswarm, violin, layered_violin, or bar

# Flag to enable to use the best run from only the latest set of CV runs (parent runs)
SELECT_FROM_LATEST_CV_RUNS: True

# test roc_auc threshold for transitioning models to staging
MIN_TEST_ROC_AUC: 0.7

# test auprc_lift threshold for transitioning models to staging
MIN_TEST_AURPC_LIFT: 2


# Random Forest hyperparameters
CLF__N_ESTIMATORS: 100
CLF__MAX_DEPTH: 40
CLF__MIN_SAMPLES_SPLIT: 15
CLF__MIN_SAMPLES_LEAF: 1