
RANDOM_STATE: 42

TRAIN_DATA_TIME_PERIOD: 1

DATABRICKS_WORKSPACE_URL: "/Users/henryhfung4_gmail.com#ext#@henryhfung4gmail.onmicrosoft.com/"

# True if running on Databricks workspace; False if running via databricks-connect
RUN_ON_DATABRICKS_WS: False
